format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
${custom.kubeselect}\
ğŸš $line_break\
$status\
$shell\
$character"""

[gcloud]
disabled = true

[git_branch]
format = "on [$branch]($style) "

[custom.kubeselect]
when = "true"
command = "/Users/zerok/bin/kubeselect status"
style = "bold blue"
